---
- name: Create a new database with name db_name
  community.mysql.mysql_db:
    login_host: localhost
    login_user: root
    login_password: "{{ db_root_password }}"
    name: "{{ db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci
    state: present