---
- name: Clone Trinitycore 3.3.5 src from git
  ansible.builtin.git:
    repo: git://github.com/TrinityCore/TrinityCore.git 
    dest: /home/vagrant/TrinityCore
    single_branch: yes
    version:  "3.3.5"

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/vagrant/TrinityCore/build
    state: directory
    mode: '0777'

- name: Run CMAKE
  ansible.builtin.command:
    chdir: /home/vagrant/TrinityCore/build
    cmd: cmake ../ -DCMAKE_INSTALL_PREFIX=/home/vagrant/server

- name: register nproc value
  ansible.builtin.command:
    cmd: nproc
  register: cpu_count

- name: Run make -j $(nproc) 
  ansible.builtin.command:
    chdir: /home/vagrant/TrinityCore/build
    cmd: make -j"{{cpu_count.stdout}}"

- name: Run make install
  ansible.builtin.command:
    chdir: /home/vagrant/TrinityCore/build
    cmd: make install

