- name: Copy WOW client to extract files
  ansible.builtin.copy:
    src: "{{client_folder}}"
    dest: /home/trinity/
    owner: trinity
    group: trinity
    mode: '0744'

- name: Copy binaries to extract files
  ansible.builtin.copy:
    src: "{{artifacts_collect_folder}}/bin/{{item}}"
    dest: /home/trinity/client/
    owner: trinity
    group: trinity
    mode: '0744'
  with_items:
  - mapextractor
  - vmap4extractor
  - vmap4assembler
  - mmaps_generator

- name: Extract files from client
  ansible.builtin.command:
    chdir: /home/trinity/client
    cmd: "/home/trinity/client/{{item}}"
  with_items:
  - mapextractor
  - vmap4extractor
  - vmap4assembler
  - mmaps_generator

- name: Copy extracted files
  ansible.builtin.copy:
    src: "/home/trinity/client/{{item}}"
    dest: /home/trinity/server/bin/
    owner: trinity
    group: trinity
    mode: '0744'
    remote_src: yes
  with_items:
  - dbc
  - maps
  - vmaps
  - mmaps
  - Cameras

- name: Remove client
  ansible.builtin.file:
    path: "/home/trinity/client"
    state: absent


