---
- name: register etc files to fetch
  ansible.builtin.command:
    chdir: /home/trinity/server
    cmd: ls etc/
  register: etc_files

- name: register bin files to fetch
  ansible.builtin.command:
    chdir: /home/trinity/server
    cmd: ls bin/
  register: bin_files

- name: fetch builded etc
  ansible.builtin.fetch:
    src: "/home/trinity/server/etc/{{item}}"
    dest: "{{artifacts_collect_folder}}/etc/"
    flat: yes
    validate_checksum: no 
  with_items: "{{etc_files.stdout_lines}}"
  become: no

- name: fetch builded bin
  ansible.builtin.fetch:
    src: "/home/trinity/server/bin/{{item}}"
    dest: "{{artifacts_collect_folder}}/bin/"
    flat: yes
    validate_checksum: no 
  with_items: "{{bin_files.stdout_lines}}"
  become: no
