---
- name: install PIP3
  apt: 
    name: "python3-pip"
    update_cache: yes
    state: present

- name: Install build deps
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - git 
  - clang 
  - cmake 
  - make 
  - gcc 
  - g++ 
  - libmariadbclient-dev 
  - libssl-dev 
  - libbz2-dev 
  - libreadline-dev 
  - libncurses-dev 
  - libboost-all-dev  
  - p7zip 
  - libmariadb-client-lgpl-dev-compat