---
- name: Add trinity server user
  ansible.builtin.user:
    name: trinity
    password: "{{ trinity_user_password | password_hash('sha512') }}"
    shell: /bin/bash
    groups: sudo
    append: yes

- name: Create a folders structure
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    mode: '0744'
    owner: trinity
    group: trinity
  with_items:
  - /home/trinity/server/bin/
  - /home/trinity/server/etc/

- name: Clone Trinitycore 3.3.5 src from git
  ansible.builtin.git:
    repo: git://github.com/TrinityCore/TrinityCore.git 
    dest: /home/trinity/TrinityCore
    single_branch: yes
    version:  "3.3.5"

- name: Copy worldserver binary
  ansible.builtin.copy:
    src: "{{artifacts_collect_folder}}/bin/worldserver"
    dest: /home/trinity/server/bin/
    owner: trinity
    group: trinity
    mode: '0744'

- name: Copy worldserver configs
  ansible.builtin.copy:
    src: "{{artifacts_collect_folder}}/etc/worldserver.conf.dist"
    dest: /home/trinity/server/etc/worldserver.conf
    owner: trinity
    group: trinity
    mode: '0744'

- name: Copy TDB_world* sql
  ansible.builtin.copy:
    src: "{{artifacts_collect_folder}}/{{TDB_world_database}}"
    dest: /home/trinity/server/bin/
    owner: trinity
    group: trinity
    mode: '0744'

