---
- name: Build trinitycore
  hosts:
  - build
  
  tasks:
  - include_role:
      name: trinitycore
      tasks_from: add_swap

  - include_role:
      name: trinitycore
      tasks_from: prepare

  - include_role:
      name: trinitycore
      tasks_from: build

  - include_role:
      name: trinitycore
      tasks_from: fetch_artifacts

  vars_files:
    ../varfile.yaml
  become: yes