---
- name: install trinitycore worldserver
  hosts:
  - worldserver
  
  tasks:
  - include_role:
      name: trinitycore
      tasks_from: prepare

  - include_role:
      name: trinitycore
      tasks_from: add_swap

  - include_role:
      name: trinitycore
      tasks_from: worldserver_up

  vars_files:
    ../varfile.yaml
  become: yes